#!/usr/bin/env python3
"""Execute code cells from the public notebook and preserve reader-facing outputs."""

from __future__ import annotations

import contextlib
import json
import sys
from io import StringIO
from pathlib import Path


def as_source(value: str | list[str]) -> str:
    if isinstance(value, list):
        return "".join(value)
    return value


def make_display(outputs: list[dict]) -> callable:
    def display(obj) -> None:
        data = {}
        if hasattr(obj, "_repr_html_"):
            data["text/html"] = obj._repr_html_()
            data["text/plain"] = repr(obj)
        elif isinstance(obj, str) and obj.lstrip().startswith("<"):
            data["text/html"] = obj
            data["text/plain"] = "HTML output"
        elif hasattr(obj, "to_html"):
            data["text/html"] = obj.to_html(index=False)
            data["text/plain"] = obj.to_string(index=False)
        else:
            data["text/plain"] = repr(obj)
        outputs.append({"output_type": "display_data", "metadata": {}, "data": data})

    return display


def write_preview(notebook: dict, preview_path: Path) -> None:
    lines = [
        "# Executed notebook preview",
        "",
        "This file is generated by `code/execute_public_notebook.py` from the executed notebook. It is a reader-facing preview of section text and preserved outputs.",
        "",
    ]
    for cell in notebook.get("cells", []):
        source = as_source(cell.get("source", ""))
        if cell.get("cell_type") == "markdown":
            lines.append(source.rstrip())
            lines.append("")
            continue
        if cell.get("cell_type") != "code":
            continue
        output_lines: list[str] = []
        for output in cell.get("outputs", []):
            if output.get("output_type") == "stream":
                text = output.get("text", "")
            elif output.get("output_type") == "display_data":
                text = output.get("data", {}).get("text/plain", "")
            else:
                text = output.get("ename", "") + ": " + output.get("evalue", "")
            if text:
                output_lines.append(str(text).rstrip())
        if output_lines:
            lines.append("```text")
            lines.append("\n\n".join(output_lines))
            lines.append("```")
            lines.append("")
    preview_path.parent.mkdir(parents=True, exist_ok=True)
    preview_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("Usage: execute_public_notebook.py NOTEBOOK.ipynb")

    notebook_path = Path(sys.argv[1]).resolve()
    artifact = notebook_path.parents[1]
    namespace = {"__name__": "__notebook__"}
    log_lines = []

    notebook = json.loads(notebook_path.read_text(encoding="utf-8"))
    old_cwd = Path.cwd()
    try:
        import os

        os.chdir(artifact)
        execution_count = 0
        for idx, cell in enumerate(notebook.get("cells", []), start=1):
            if cell.get("cell_type") != "code":
                continue
            if cell.get("metadata", {}).get("browser_only"):
                log_lines.append(f"SKIP browser-only cell {idx}")
                cell["execution_count"] = None
                cell["outputs"] = []
                continue
            source = as_source(cell.get("source", ""))
            outputs: list[dict] = []
            namespace["display"] = make_display(outputs)
            stdout = StringIO()
            execution_count += 1
            with contextlib.redirect_stdout(stdout):
                exec(compile(source, f"{notebook_path.name}:cell{idx}", "exec"), namespace)
            printed = stdout.getvalue()
            if printed:
                outputs.insert(0, {"output_type": "stream", "name": "stdout", "text": printed})
            cell["execution_count"] = execution_count
            cell["outputs"] = outputs
            log_lines.append(f"PASS cell {idx}")
    finally:
        import os

        os.chdir(old_cwd)

    notebook_path.write_text(json.dumps(notebook, indent=2) + "\n", encoding="utf-8")
    write_preview(notebook, artifact / "docs" / "notebook_executed_preview.md")

    log_path = artifact / "qa" / "notebook_execution_log.txt"
    log_path.write_text("\n".join(log_lines) + "\n", encoding="utf-8")
    print(f"PASS public notebook execution: {log_path}")


if __name__ == "__main__":
    main()
